name: Publish on Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run GraphQL Codegen
        run: npm run codegen

      - name: Pack the SDK
        run: npm pack

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set version from tag
        run: |
          # Extract the tag name and update the package.json version
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Setting version to $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git push

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
